version: "3.8"

services:
  server:
    image: server:0.0.1
    container_name: server
    ports:
      - "8080:8080"
    networks:
      - webnet

  prometheus:
    image: prom/prometheus:v2.40.7
    container_name: prometheus
    ports:
      - "9090:9090"
    networks:
      - webnet
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro

  grafana:
    image: grafana/grafana:9.4.2
    container_name: grafana
    ports:
      - "3000:3000"
    networks:
      - webnet
    volumes:
      - ./grafana/config.ini:/etc/grafana/grafana.ini
      - ./grafana/datasource.yml:/etc/grafana/provisioning/datasources/default.yaml
      - ./grafana/dashboard.yml:/etc/grafana/provisioning/dashboards/default.yaml
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    restart: unless-stopped

networks:
  webnet:
    driver: bridge
